defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "step_{step:06d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  every_n_train_steps: 10_000

model_summary:
  max_depth: 4
